#ifndef DEFINICIONES_H
#define DEFINICIONES_H


// ASCII
#define LF 10
#define OP_SUMA 43
#define OP_RESTA 45
#define OP_MULTIPLICACION 42
#define OP_DIVISION 47
#define OP_EQUAL 61
#define OP_MENOR 60
#define OP_MAYOR 62
#define OP_DOS_PUNTOS 58
#define OP_PUNTO 46

#define DELIM_CORCHETE_ABRIR 91
#define DELIM_CORCHETE_CERRAR 93
#define DELIM_PARENTESIS_ABRIR 40
#define DELIM_PARENTESIS_CERRAR 41
#define DELIM_LLAVE_ABRIR 123
#define DELIM_LLAVE_CERRAR 125
#define DELIM_COMA 44
#define DELIM_PUNTO_Y_COMA 59


//OPERADORES Y DELIMITADORES
#define OP_SUMA_ASIGNACION 410
#define OP_FLECHA 412
#define OP_RESTA_ASIGNACION 413
#define OP_MULTI_ASIGNACION 414
#define OP_DIV_ASIGNACION 415
#define OP_EQUAL_EQUAL 416
#define OP_MENOR_EQUAL 417
#define OP_POTENCIA 418
#define OP_MAYOR_EQUAL 419
#define OP_DOS_PUNTOS_EQUAL 420

//TIPOS
#define INTEGER 450
#define FLOAT 451
#define STRING 452
#define IDENTIFICADOR 302


//PALABRAS RESERVADAS
#define IMPORT 300
#define AS 301
#define FOR 303
#define IF 304
#define WHILE 305
#define DEF 306
#define IN 307
#define ELIF 308
#define ELSE 309
#define RETURN 310
#define NOT 311


#endif // DEFINICIONES_H